### ISSUE TITLE
Deployed site gives 404

### ISSUE THREAD

**Issue by mao-sz** [fabulousgk/fabulous-styleboard#2]
With the username change (love it), https://fabulousgk.github.io/fabulous-styleboard/ is no longer valid and returns a 404. It's used as an additional resource in TOP.

**Comment by UniquePixels** [comment]
Ahh crud, woops

**Comment by UniquePixels** [comment]
@MaoShizhong it is fixed, I created an org using the old username and transferred the repo to it.
